apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plain-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: plain.[cluster-name].confidential.cloud
    http:
      paths:
      - backend:
          service:
            name: plain-service
            port:
              number: 8081
        path: /
        pathType: Prefix
