apiVersion: v1
kind: Service
metadata:
  annotations:
    contrast.edgeless.systems/expose-service: "true"
  labels:
    app: demo
  name: demo-lb-svc
spec:
  ports:
  - name: https
    port: 443
    targetPort: 8081
  selector:
    app: demo
  sessionAffinity: None
  type: LoadBalancer
